//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Cost { get; set; }
        public int Client_ID { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
