//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Details
    {
        public int ID { get; set; }
        public int Sales_ID { get; set; }
        public int Index { get; set; }
        public int Nomenclature_ID { get; set; }
        public decimal Price { get; set; }
        public decimal Count { get; set; }
    
        public virtual Nomenclature Nomenclature { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
